name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env : 
        DOCKER_USER : javadjazz123
        DOCKER_PASSWORD : dckr_pat_5NuwQe-acnhN350DEO8mgCU0mxA
      run: |
        docker login -u javadjazz123 -p dckr_pat_5NuwQe-acnhN350DEO8mgCU0mxA 
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag javadjazz123/mini-com:master
    
    - name: Docker Push
      run: docker push javadjazz123/mini-com:master